### ISSUE TITLE
Use Mi instead of M for memory limits

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#1087]
We are passing `M` to Kubernetes which k8s/kubelet interprets as SI unit (10^6) and then gives it to docker.  However, developers expected to pass to Docker to be `Mi`, meaning binary (2^20).

Lines to fix: 

For SaaS: https://github.com/blackducksoftware/synopsys-operator/blob/saas-2019.8.4/pkg/apps/blackduck/latest/containers/constants.go#L73

For Onprem: https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/pkg/apps/blackduck/latest/containers/constants.go#L73

**How to reproduce it (as minimally and precisely as possible)**:

`docker run -d --name test-stress -m 2560M polinux/stress stress --vm 1 --vm-bytes 2560M --timeout 10m --verbose`
`docker inspect test-stress`

memory will look like this which is binary ((2**20)*2560)
"Memory": 2684354560

Pass this spec to k8s

```
apiVersion: v1
kind: Pod
metadata:
 name: memory-demo
 namespace: mem-example
spec:
 nodeName: worker0-yashb-2019-10-28-ci-kube1-15-3-1m4w
 containers:
 - name: memory-demo-ctr
 image: polinux/stress
 resources:
 limits:
 memory: "2560M"
 requests:
 memory: "2048M"
 command: ["stress"]
 args: ["--vm", "1", "--vm-bytes", "2460M", "--vm-hang", "1", "--timeout", "10m", "--verbose"]
```

docker inspect <Container Id of the pod> or look at `/sys/fs/cgroup/memory/<PID>/memory.limit_in_bytes`

this will look like this which is SI unit ((10**6)*2560)
"Memory": 256000000

Further details in comments [here](https://jira-sig.internal.synopsys.com/browse/HUB-22114)

**Screenshots/additional context**:
Cross-ref: [HUB-22114](https://jira-sig.internal.synopsys.com/browse/HUB-22114)

[Kubernetes Docs Meaning on Memory](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory)
