### ISSUE TITLE
Corrupted hubs cause system-wide issues

### ISSUE THREAD

**Issue by rpiskule-syn** [blackducksoftware/synopsys-operator#905]
**What happened**:
A hub deployed using a CR was corrupted. It resulted in an infinite failure loop in operator.

**What you expected to happen**:
New (properly formatted hubs) can be created and the failure for this specific hub is ignored.

**How to reproduce it (as minimally and precisely as possible)**:
The final key `- {}` somehow ended up in my hub. It would be nice if this didn't cause a cluster-wide issue.
```
- apiVersion: synopsys.com/v1
  kind: Blackduck
  spec:
    environs:
    - HUB_SAML_EXTERNAL_URL:https://example.com
    - USE_ALERT:0
    - USE_BINARY_UPLOADS:0
    - {}
```
